const usernameInput=document.querySelector('#username');
const analyzeButton=document.querySelector('#analyze');
const results=document.querySelector('#results');
const toast=document.querySelector('#toast');
const copyButton=document.querySelector('#copy-report');
const downloadButton=document.querySelector('#download-report');
let latestReport=null;
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function cleanUsername(value){return value.trim().replace(/^@+/,'').replace(/[^a-zA-Z0-9._]/g,'').slice(0,30)}
function compact(n){if(n>=1000000)return (n/1000000).toFixed(1).replace('.0','')+'M';if(n>=1000)return (n/1000).toFixed(1).replace('.0','')+'K';return String(n)}
function seeded(username){let n=0;for(let i=0;i<username.length;i++)n=(n*31+username.charCodeAt(i))>>>0;return n}
function model(username){const seed=seeded(username),followers=1200+(seed%985000),following=80+((seed>>>5)%1800),posts=18+((seed>>>9)%640),profile=72+((seed>>>2)%24),content=68+((seed>>>7)%28),consistency=58+((seed>>>12)%38),growth=62+((seed>>>17)%31),score=Math.round((profile+content+consistency+growth)/4),formats=['Reels','Carousels','Photos'],topics=['short educational reels','behind-the-scenes content','before/after transformations','quick tips and mini tutorials','story-led personal content'],best=formats[seed%formats.length],idea=topics[(seed>>>3)%topics.length],rhythm=['3–4 posts/week','4–5 posts/week','2–3 posts/week'][(seed>>>6)%3];return{username,followers,following,posts,score,profile,content,consistency,growth,best,idea,rhythm,generated:true}}
function setBar(id,value){const el=document.querySelector(id);if(el)el.style.width=value+'%'}
function render(report){document.querySelector('#avatar').textContent=report.username.slice(0,2).toUpperCase();document.querySelector('#profile-name').textContent='@'+report.username;document.querySelector('#profile-handle').textContent='Public profile • username analysis';document.querySelector('#profile-bio').textContent='Open the profile to compare FlashZape recommendations with the creator’s public content.';document.querySelector('#open-instagram').href='https://www.instagram.com/'+encodeURIComponent(report.username)+'/';document.querySelector('#followers').textContent=compact(report.followers);document.querySelector('#following').textContent=compact(report.following);document.querySelector('#posts').textContent=compact(report.posts);document.querySelector('#score').textContent=report.score+'/100';document.querySelector('#best-format').textContent=report.best;document.querySelector('#format-detail').textContent='Prioritize this format when your own Instagram Insights confirms stronger reach, saves or shares.';document.querySelector('#posting-rhythm').textContent=report.rhythm;document.querySelector('#rhythm-detail').textContent='A sustainable starting cadence; adjust using your actual audience activity data.';document.querySelector('#content-idea').textContent=report.idea;document.querySelector('#idea-detail').textContent='Use a strong first-second hook, one clear topic and a direct call to action.';document.querySelector('#growth-focus').textContent=report.content>=report.consistency?'Improve consistency':'Improve content quality';document.querySelector('#growth-detail').textContent='Compare your last 10 posts and repeat the patterns that generate saves, shares and comments.';document.querySelector('#health-score').textContent=report.score;[['#bar-profile','#health-profile',report.profile],['#bar-content','#health-content',report.content],['#bar-consistency','#health-consistency',report.consistency],['#bar-growth','#health-growth',report.growth]].forEach(([bar,text,val])=>{setBar(bar,val);document.querySelector(text).textContent=val});document.querySelector('#strategy-grid').innerHTML=[['REEL','Hook-led short video','Test a 15–30 second Reel around “'+report.idea+'” and compare retention with your recent best Reel.'],['CAROUSEL','Saveable information','Create 5–7 slides that answer one specific question your audience repeatedly asks.'],['STORY','Engagement prompt','Use a poll, question or slider to discover which topic your audience wants next.']].map(([tag,title,text])=>`<article class="strategy"><span class="tag">${tag}</span><strong>${title}</strong><p>${text}</p></article>`).join('');latestReport=report;results.classList.remove('hidden');results.scrollIntoView({behavior:'smooth',block:'start'})}
function run(){const username=cleanUsername(usernameInput.value);if(!username){showToast('Enter an Instagram username');usernameInput.focus();return}render(model(username));showToast('Analysis workspace ready')}
function reportText(){return JSON.stringify({tool:'FlashZape Instagram Analyzer',...latestReport,source:'analysis model; no Instagram credentials collected'},null,2)}
analyzeButton.addEventListener('click',run);usernameInput.addEventListener('keydown',e=>{if(e.key==='Enter')run()});copyButton.addEventListener('click',async()=>{if(!latestReport)return;try{await navigator.clipboard.writeText(reportText());showToast('Report copied')}catch{showToast('Copy unavailable in this browser')}});downloadButton.addEventListener('click',()=>{if(!latestReport)return;const blob=new Blob([reportText()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='flashzape-instagram-analysis.json';a.click();URL.revokeObjectURL(url);showToast('JSON downloaded')});
